### ISSUE TITLE
EpubCheck 4 on Android platform 

### ISSUE THREAD

**Issue by DhairyashilBhosale** [IDPF/epubcheck#641]
Hi all, 
         I am trying to import EpubCheck4 jar file in Android code and I successful import Epubchecker4.jar in Android Studio and trying to validate EPUB files like:

```
@Override
    public void onClick(View v) {

        if(v.getId() == R.id.validateBtn){
            File sdcard = Environment.getExternalStorageDirectory();
            File epubFile = new File(sdcard,"/Download/test.epub");
            EpubCheck epubCheck = new EpubCheck(epubFile);
            //EpubCheck epubCheck = new EpubCheck(epubFile);
            result = epubCheck.validate();
            Toast.makeText(MainActivity.this," path: "+epubFile+" :result: "+result, Toast.LENGTH_LONG).show();
        }
    }
```
On Button click I am trying to validate EPUB file, but I got following exceptions like:

```

.epubchecker E/AndroidRuntime: FATAL EXCEPTION: main
.epubchecker E/AndroidRuntime: Process: com.example.nrcfoss.epubchecker, PID: 28519
.epubchecker E/AndroidRuntime: java.lang.ExceptionInInitializerError
.epubchecker E/AndroidRuntime:     at com.adobe.epubcheck.api.MasterReport.<init>(MasterReport.java:25)
.epubchecker E/AndroidRuntime:     at com.adobe.epubcheck.util.DefaultReportImpl.<init>(DefaultReportImpl.java:43)
.epubchecker E/AndroidRuntime:     at com.adobe.epubcheck.util.DefaultReportImpl.<init>(DefaultReportImpl.java:39)
.epubchecker E/AndroidRuntime:     at com.adobe.epubcheck.api.EpubCheck.<init>(EpubCheck.java:98)
.epubchecker E/AndroidRuntime:     at com.example.nrcfoss.epubchecker.MainActivity.onClick(MainActivity.java:57)
.epubchecker E/AndroidRuntime:     at android.view.View.performClick(View.java:4761)
.epubchecker E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19767)
.epubchecker E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
.epubchecker E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
.epubchecker E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
.epubchecker E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5312)
.epubchecker E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
.epubchecker E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
.epubchecker E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
.epubchecker E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
.epubchecker E/AndroidRuntime:  Caused by: java.util.MissingResourceException
.epubchecker E/AndroidRuntime:     at java.util.ResourceBundle.getBundle(ResourceBundle.java:327)
.epubchecker E/AndroidRuntime:     at java.util.ResourceBundle.getBundle(ResourceBundle.java:271)
.epubchecker E/AndroidRuntime:     at com.adobe.epubcheck.messages.MessageDictionary.<clinit>(MessageDictionary.java:54)
.epubchecker E/AndroidRuntime:     at com.adobe.epubcheck.api.MasterReport.<init>(MasterReport.java:25) 
.epubchecker E/AndroidRuntime:     at com.adobe.epubcheck.util.DefaultReportImpl.<init>(DefaultReportImpl.java:43) 
.epubchecker E/AndroidRuntime:     at com.adobe.epubcheck.util.DefaultReportImpl.<init>(DefaultReportImpl.java:39) 
.epubchecker E/AndroidRuntime:     at com.adobe.epubcheck.api.EpubCheck.<init>(EpubCheck.java:98) 
.epubchecker E/AndroidRuntime:     at com.example.nrcfoss.epubchecker.MainActivity.onClick(MainActivity.java:57) 
.epubchecker E/AndroidRuntime:     at android.view.View.performClick(View.java:4761) 
.epubchecker E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19767) 
.epubchecker E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739) 
.epubchecker E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95) 
.epubchecker E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
.epubchecker E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5312) 
.epubchecker E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
.epubchecker E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
.epubchecker E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901) 
.epubchecker E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696) 
```

1) Epubchecker4.jar works in Android Code? 
2) How to use EpubChecker in Android platform?

**Comment by rdeltour** [comment]
> 1) Epubchecker4.jar works in Android Code? 

It's not a platform that is officially supported by EpubCheck, but it might work.

> 2) How to use EpubChecker.jar in Android platform?

I don't know. Being runnable on Android is not a priority for EpubCheck, so basically your on your own to make it work. We can keep this thread open in case others want to help or join the discussion here.
