### ISSUE TITLE
epubcheck fails with Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by jcdarwin** [IDPF/epubcheck#644]
Can someone help with this -- running https://github.com/IDPF/epubcheck/releases/tag/v4.0.1 at the command line:

    java -jar epubcheck.jar book.epub

I get the following exception:

    Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:266)
        at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
    Caused by: java.util.MissingResourceException: Can't find bundle for base name com.adobe.epubcheck.util.messages, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:890)
        at com.adobe.epubcheck.util.Messages.<clinit>(Messages.java:43)
        ... 2 more
    Caused by: java.lang.NoClassDefFoundError: com/google/common/base/Charsets
        at com.adobe.epubcheck.util.Messages$UTF8Control.newBundle(Messages.java:109)
        at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1501)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1465)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1419)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1419)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1361)
        ... 4 more
    Caused by: java.lang.ClassNotFoundException: com.google.common.base.Charsets
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 10 more

This occurs on Mac OSX 10.11, using java 1.8.0_05, i.e.

    java -version

    java version "1.8.0_05"
    Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

Running epubcheck 3.0.1 at the command line works fine.

**Comment by rdeltour** [comment]
Have you moved the jar file out of its unzipped directory? EpubCheck needs the third-party libraries in the `lib` folder to run correctly.

**Comment by jcdarwin** [comment]
Great -- yep, I'd missed updating the jars in /lib -- that solves it.

I do have another problem though when building 4.0.1 from src -- I'll open another ticket for that shortly.
