### ISSUE TITLE
Java OutOfMemoryError : Java heap space

### ISSUE THREAD

**Issue by vincent-gros** [IDPF/epubcheck#652]
Seen this error with an EPUB2 file:

```
Validating using EPUB version 2.0.1 rules.
java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferByte.<init>(Unknown Source)
	at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
	at java.awt.image.Raster.createWritableRaster(Unknown Source)
	at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
	at javax.imageio.ImageReader.getDestination(Unknown Source)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(Unknown Source)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at com.adobe.epubcheck.bitmap.BitmapChecker.getImageSizes(BitmapChecker.java:144)
	at com.adobe.epubcheck.bitmap.BitmapChecker.checkImageDimensions(BitmapChecker.java:268)
	at com.adobe.epubcheck.bitmap.BitmapChecker.runChecks(BitmapChecker.java:320)
	at com.adobe.epubcheck.opf.OPFChecker.checkItemContent(OPFChecker.java:423)
	at com.adobe.epubcheck.opf.OPFChecker.runChecks(OPFChecker.java:157)
	at com.adobe.epubcheck.ocf.OCFChecker.runChecks(OCFChecker.java:300)
	at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:215)
	at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:160)
	at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:494)
	at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:254)
	at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
epubcheck completed
```

**Comment by santoch** [comment]
You are likely using the default heap size, which while adequate for most books, sometimes isn't enough for others.

try java -Xmx512m -jar epubcheck.jar <then your book name here>

in this case, I specified 512 megabytes heap space
you can try various sizes (-Xmx2g gives 2 gigs,  etc)
you can also add it to your JAVA_OPTS environment variable so that it defaults to that instead.

linux/mac:
declare -X JAVA_OPTS='-Xmx2g'

windows:
set JAVA_OPTS=-Xmx2g

**Comment by vincent-gros** [comment]
Thank you @santoch.
It works perfectly.
