### ISSUE TITLE
"Exception in thread..." when running epubcheck

### ISSUE THREAD

**Issue by deborah-ufw** [IDPF/epubcheck#699]
epubcheck.jar materialized after "mvn install" despite mvn error, so I tried to run it (Mac OSX El Capitan). 

None of the files have been moved - epubcheck.jar is in the directory above /lib.

Error:

    Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:266)
	at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
Caused by: java.util.MissingResourceException: Can't find bundle for base name com.adobe.epubcheck.util.messages, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:890)
	at com.adobe.epubcheck.util.Messages.<clinit>(Messages.java:43)
	... 2 more

**Comment by tofi86** [comment]
Related to #698

**Comment by tofi86** [comment]
Can you try again with the download from the "releases page" in a clean directory?
