### ISSUE TITLE
maven build/tests fail on windows

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#719]
On my windows system @ work I cannot build or test the project as it always fails with those errors:

```
java.lang.RuntimeException: File /C:/Users/TobiasFischer/github/epubcheck/target/test-classes/30/single/opf/valid/base-001.opf does not exist
	at com.adobe.epubcheck.util.FileResourceProvider.<init>(FileResourceProvider.java:41)
	at com.adobe.epubcheck.opf.OPFCheckerTest.testValidateDocument(OPFCheckerTest.java:97)
	at com.adobe.epubcheck.opf.OPFCheckerTest.testValidateDocument(OPFCheckerTest.java:63)
	at com.adobe.epubcheck.opf.OPFCheckerTest.testValidateDocument(OPFCheckerTest.java:57)
	at com.adobe.epubcheck.opf.OPFCheckerTest.testValidateDocumentValidOPFBase001(OPFCheckerTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

The file `C:/Users/TobiasFischer/github/epubcheck/target/test-classes/30/single/opf/valid/base-001.opf` exists(!), but when trying to get the file path from the class resources (e.g. in [OPFCheckerTest.java l.92 ff](https://github.com/IDPF/epubcheck/blob/master/src/test/java/com/adobe/epubcheck/opf/OPFCheckerTest.java#L92)

```java
URL fileURL = this.getClass().getResource(basepath + fileName);
String filePath = fileURL != null ? fileURL.getPath() : basepath + fileName;
```
the `fileURL.getPath()` strips the `file:/` from the URL, leaving a single slash at the beginning of the path, resulting in:
```
java.lang.RuntimeException: File /C:/Users/TobiasFischer/github/epubcheck/target/test-classes/30/single/opf/valid/base-001.opf does not exist
```

**Comment by tofi86** [comment]
Solution would be to use `new File(fileURL.toURI()).getAbsolutePath()` instead of `fileURL.getPath()`.

However, this needs a try/catch arround it, making the refactoring a bit bigger...

Plus it's not only the `OPFCheckerTest` class which is affected, there's many more. `OPFCheckerTest` was just an example...

**Comment by tofi86** [comment]
I found stashed changes on my windows machine @ work which almost fixed all of those tests. I just completed the bugfix and pushed to a separate branch.

@rdeltour could you please review?
