### ISSUE TITLE
Unable to execute the program. Different types of errors come up

### ISSUE THREAD

**Issue by Madhu-P** [IDPF/epubcheck#755]
When i run the EPUBcheck with proper arguments, i am facing the following errors

```
org.xml.sax.SAXParseException; systemId: file:/C:/Users/workspace/EpubCheck/bin/com/adobe/epubcheck/schema/30/multiple-renditions/container.sch; lineNumber: 2; columnNumber: 75; no implementation available for schema language with namespace URI "http://purl.oclc.org/dsdl/schematron"
	at com.thaiopensource.validate.auto.AutoSchemaReceiver$Handler.startElement(AutoSchemaReceiver.java:52)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:506)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:376)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3065)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:881)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:607)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:116)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:489)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:835)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1210)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:568)
	at com.thaiopensource.validate.auto.AutoSchemaReader.createSchema(AutoSchemaReader.java:69)
	at com.thaiopensource.validate.AbstractSchemaReader.createSchema(AbstractSchemaReader.java:13)
	at com.adobe.epubcheck.xml.XMLValidator.<init>(XMLValidator.java:249)
	at com.adobe.epubcheck.xml.XMLValidators.<init>(XMLValidators.java:56)
	at com.adobe.epubcheck.xml.XMLValidators.<clinit>(XMLValidators.java:7)
	at com.adobe.epubcheck.ocf.OCFChecker.<clinit>(OCFChecker.java:70)
	at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:213)
	at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:160)
	at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:494)
	at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:254)
	at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)

java.lang.Error: Internal error: org.xml.sax.SAXParseException; systemId: file:/C:/Users/workspace/EpubCheck/bin/com/adobe/epubcheck/schema/30/multiple-renditions/container.sch; lineNumber: 2; columnNumber: 75; no implementation available for schema language with namespace URI "http://purl.oclc.org/dsdl/schematron" schema/30/multiple-renditions/container.sch
	at com.adobe.epubcheck.xml.XMLValidator.<init>(XMLValidator.java:259)
	at com.adobe.epubcheck.xml.XMLValidators.<init>(XMLValidators.java:56)
	at com.adobe.epubcheck.xml.XMLValidators.<clinit>(XMLValidators.java:7)
	at com.adobe.epubcheck.ocf.OCFChecker.<clinit>(OCFChecker.java:70)
	at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:213)
	at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:160)
	at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:494)
	at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:254)
	at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
```

I have included all the necessary jar files. But i dnt understand where is the issue

**Comment by tofi86** [comment]
*edited original message to properly mark code as preformatted*

**Comment by tofi86** [comment]
Please answer the following questions:
1. Do you run EpubCheck from another Java program?
2. Do you run it with Maven support (as a maven dependency) or did you place all the JAR files in your classpath.
3. Can you print the classpath of your program?

It looks like a jar is missing.

**Comment by Madhu-P** [comment]
1. I am not running EpubCheck from other Java program. 
2. I have placed all the jars in the build path.
3. Here is the classpath of my program: 

<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src/main/resources"/>
	<classpathentry kind="src" path="src/main/java"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7"/>
	<classpathentry kind="lib" path="C:/JarFiles/commons-compress-1.5.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/epubcheck-4.0.1.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/guava-14.0.1.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/imageio-core-3.1.2.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/jackson-core-asl-1.9.12.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/jackson-mapper-asl-1.9.2.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/jing-20091111.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/junit-4.10.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/sac-1.3.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/Saxon-HE-9.5.1-5.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/xml-apis-2.0.2.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/xmlunit-1.3.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/xz-1.0.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>

**Comment by Madhu-P** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src/main/resources"/>
	<classpathentry kind="src" path="src/main/java"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7"/>
	<classpathentry kind="lib" path="C:/JarFiles/commons-compress-1.5.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/epubcheck-4.0.1.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/guava-14.0.1.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/imageio-core-3.1.2.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/jackson-core-asl-1.9.12.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/jackson-mapper-asl-1.9.2.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/jing-20091111.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/junit-4.10.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/sac-1.3.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/Saxon-HE-9.5.1-5.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/xml-apis-2.0.2.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/xmlunit-1.3.jar"/>
	<classpathentry kind="lib" path="C:/JarFiles/xz-1.0.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>

**Comment by tofi86** [comment]
Note: you can use preformatted text blocks with three (3) backticks `
I edited your comment for better readability...

**Comment by tofi86** [comment]
First: you are using EpubCheck 4.0.1 which has a severe security issue! Please update to version 4.0.2 ASAP!! https://github.com/IDPF/epubcheck/releases/tag/v4.0.2

Then: 
> I have placed all the jars in the build path.

NO, you did NOT! Your classpath is missing quite a lot of libs... Please update your project sources.

**Comment by Madhu-P** [comment]
Could you specify which all libs i am missing? Is there any link for list of libs?

**Comment by Madhu-P** [comment]
I have used epubcheck 4.0.2. And Now, i get these errors:

```
`org.xml.sax.SAXParseException; systemId: file:/C:/Users/1191914/workspace_madhu/EpubCheck/bin/com/adobe/epubcheck/schema/30/media-overlay-30.sch; lineNumber: 9; columnNumber: 10; element "schema" incomplete; missing required element "pattern"
	at com.thaiopensource.relaxng.sax.PatternValidator.check(PatternValidator.java:116)
	at com.thaiopensource.relaxng.sax.PatternValidator.endElement(PatternValidator.java:56)
	at com.thaiopensource.xml.sax.ForkContentHandler.endElement(ForkContentHandler.java:48)
	at com.thaiopensource.validate.schematron.IfValidHandler.endElement(IfValidHandler.java:77)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1742)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2900)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:607)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:116)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:489)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:835)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1210)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:568)
	at com.thaiopensource.validate.schematron.ISOSchemaReaderImpl.createSchema(ISOSchemaReaderImpl.java:372)
	at com.thaiopensource.validate.auto.SchemaReaderSchemaReceiver$1.reparse(SchemaReaderSchemaReceiver.java:25)
	at com.thaiopensource.validate.auto.AutoSchemaReader.createSchema(AutoSchemaReader.java:75)
	at com.thaiopensource.validate.AbstractSchemaReader.createSchema(AbstractSchemaReader.java:13)
	at com.adobe.epubcheck.xml.XMLValidator.<init>(XMLValidator.java:249)
	at com.adobe.epubcheck.xml.XMLValidators.<init>(XMLValidators.java:56)
	at com.adobe.epubcheck.xml.XMLValidators.<clinit>(XMLValidators.java:16)
	at com.adobe.epubcheck.ocf.OCFChecker.<clinit>(OCFChecker.java:70)
	at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:213)
	at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:160)
	at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:494)
	at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:254)
	at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
com.thaiopensource.validate.IncorrectSchemaException
	at com.thaiopensource.validate.schematron.ISOSchemaReaderImpl.createSchema(ISOSchemaReaderImpl.java:377)
	at com.thaiopensource.validate.auto.SchemaReaderSchemaReceiver$1.reparse(SchemaReaderSchemaReceiver.java:25)
	at com.thaiopensource.validate.auto.AutoSchemaReader.createSchema(AutoSchemaReader.java:75)
	at com.thaiopensource.validate.AbstractSchemaReader.createSchema(AbstractSchemaReader.java:13)
	at com.adobe.epubcheck.xml.XMLValidator.<init>(XMLValidator.java:249)
	at com.adobe.epubcheck.xml.XMLValidators.<init>(XMLValidators.java:56)
	at com.adobe.epubcheck.xml.XMLValidators.<clinit>(XMLValidators.java:16)
	at com.adobe.epubcheck.ocf.OCFChecker.<clinit>(OCFChecker.java:70)
	at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:213)
	at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:160)
	at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:494)
	at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:254)
	at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
java.lang.Error: Internal error: com.thaiopensource.validate.IncorrectSchemaException schema/30/media-overlay-30.sch
	at com.adobe.epubcheck.xml.XMLValidator.<init>(XMLValidator.java:259)
	at com.adobe.epubcheck.xml.XMLValidators.<init>(XMLValidators.java:56)
	at com.adobe.epubcheck.xml.XMLValidators.<clinit>(XMLValidators.java:16)
	at com.adobe.epubcheck.ocf.OCFChecker.<clinit>(OCFChecker.java:70)
	at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:213)
	at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:160)
	at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:494)
	at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:254)
	at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)`

**Comment by tofi86** [comment]
> Could you specify which all libs i am missing? Is there any link for list of libs?

Download the ZIP file and place ALL Jars from the `lib/` folder in your classpath. You have been meissing quite a lot (e.g. `common-image-3.1.2.jar`), but I won't list them all here.... That should be an easy task for you to compare the files from `lib/` folder with the ones in your classpath... ;-)

If you switched to EpubCheck 4.0.2, please update your classpath as some of the libs may have changed from previous version.

If you updated the classpath accordingly with ALL the libs from the 4.0.2 release lib folder, and you still have problems, feel free to reopen this issue but add your current classpath in the comment...

**Comment by Madhu-P** [comment]
I have done each and everything according to your last comment. Please check my classpath and same the error which i am facing.

```
`<classpath>
	<classpathentry kind="src" path="src/main/resources"/>
	<classpathentry kind="src" path="src/main/java"/>
	<classpathentry exported="true" kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7"/>
	<classpathentry kind="lib" path="lib/common-image-3.1.2.jar"/>
	<classpathentry kind="lib" path="lib/common-io-3.1.2.jar"/>
	<classpathentry kind="lib" path="lib/common-lang-3.1.2.jar"/>
	<classpathentry kind="lib" path="lib/commons-compress-1.5.jar"/>
	<classpathentry kind="lib" path="lib/epubcheck-4.0.2.jar"/>
	<classpathentry kind="lib" path="lib/guava-14.0.1.jar"/>
	<classpathentry kind="lib" path="lib/imageio-core-3.1.2.jar"/>
	<classpathentry kind="lib" path="lib/imageio-jpeg-3.1.2.jar"/>
	<classpathentry kind="lib" path="lib/imageio-metadata-3.1.2.jar"/>
	<classpathentry kind="lib" path="lib/jackson-core-asl-1.9.12.jar"/>
	<classpathentry kind="lib" path="lib/jackson-mapper-asl-1.9.12.jar"/>
	<classpathentry kind="lib" path="lib/jackson-mapper-asl-1.9.2.jar"/>
	<classpathentry kind="lib" path="lib/jing-20091111.jar"/>
	<classpathentry kind="lib" path="lib/jing-20120724.0.0.jar"/>
	<classpathentry kind="lib" path="lib/junit-4.10.jar"/>
	<classpathentry kind="lib" path="lib/sac-1.3.jar"/>
	<classpathentry kind="lib" path="lib/Saxon-HE-9.5.1-5.jar"/>
	<classpathentry kind="lib" path="lib/xml-apis-2.0.2.jar"/>
	<classpathentry kind="lib" path="lib/xmlunit-1.3.jar"/>
	<classpathentry kind="lib" path="lib/xz-1.0.jar"/>
	<classpathentry kind="output" path="bin"/>
</classpath>`

**Comment by tofi86** [comment]
Now you're having duplicates in your classpath: `jackson-mapper-asl-1.9.12.jar` and `jackson-mapper-asl-1.9.2.jar` or `jing-20091111.jar` and `jing-20120724.0.0.jar`

Also `xml-apis-2.0.2.jar`, `xmlunit-1.3.jar`, `xz-1.0.jar`, `junit-4.10.jar` are not part of EpubCheck. Can you temporarily disable them to see whether they are causing problems?

How do you call EpubCheck in Java? Are you following these instructions? https://github.com/IDPF/epubcheck/wiki/Library
